deploy-anvil:
	forge script script/01_DeployAnvil.s.sol --rpc-url http://localhost:8545 --broadcast
do-some-transactions:
	forge script script/02_DoSomeTransactions.s.sol --rpc-url http://localhost:8545 --broadcast
